# Minecraft item that will be used a the wallet item.
wallet-item: LEATHER
# How much money will be taxed from each transaction at an ATM
atm-transaction-fee: 20.0
# Necesary amount of a shop item to start getting a discount.
# Ex. If there is more than 300 stock, apply discount.
npcshop-stock-amount-discount: 300
# Distance (in blocks) from the player at which NPCs will look at the player.
npc-look-distance: 60