# How much money will be taxed from each transaction at an ATM
atm-transaction-fee:

# Necesary amount of a shop item to start getting a discount.
# Ex. If there is more than 300 stock, apply discount.
npcshop-stock-amount-discount: 300

wallet-item: LEATHER